# Проект "Маркет"

## Цель проекта: 
- Предсказать вероятность покупки в течении 90 дней

## План проекта:
- Изучить данные
- Разработать полезные признаки
- Создать модель для классификации пользователей
- Улучшить модель и максимизировать метрику ROC_AUC
- Выполнить тестирование

## Описание данных:

**apparel-purchases**
"история покупок"
- client id идентификатор пользователя
- quantity количество товаров в заказе
- price цена товара
- category_ids вложенные категории, к которым отнсится товар
- date дата покупки
- message_id идентификатор сообщения из рассылки

**apparel-messages**
"история рекламных рассылок"
- bulk_campaign_id идентификатор рекламной кампании
- client_id идентификатор пользователя
- message_id идентификатор сообщений
- event тип действия
- channel канал рассылки
- date дата рассылки
- created_at точное время создания сообщения

**apparel-target_binary**
"совершит ли клиент покупку в течение следующих 90 дней"
- client_id идентификатор пользователя
- target целевой признак

## 1. Загрузка данных.

Для начала загрузим необходимые библиотеки, а после загрузим и откроем наши датасеты.

In [1]:
import pandas as pd

In [11]:
purchases = pd.read_csv('data/apparel-purchases.csv')
messages = pd.read_csv('data/apparel-messages.csv')
target = pd.read_csv('data/apparel-target_binary.csv')

In [13]:
display(purchases.head())
print(purchases.shape)
print('-' * 30)
display(messages.head())
print(messages.shape)
print('-' * 30)
display(target.head())
print(target.shape)

,client_id,quantity,price,category_ids,date,message_id
0,1515915625468169594,1,1999.0,"['4', '28', '57', '431']",2022-05-16,1515915625468169594-4301-627b661e9736d
1,1515915625468169594,1,2499.0,"['4', '28', '57', '431']",2022-05-16,1515915625468169594-4301-627b661e9736d
2,1515915625471138230,1,6499.0,"['4', '28', '57', '431']",2022-05-16,1515915625471138230-4437-6282242f27843
3,1515915625471138230,1,4999.0,"['4', '28', '244', '432']",2022-05-16,1515915625471138230-4437-6282242f27843
4,1515915625471138230,1,4999.0,"['4', '28', '49', '413']",2022-05-16,1515915625471138230-4437-6282242f27843

(202208, 6)
------------------------------

,bulk_campaign_id,client_id,message_id,event,channel,date,created_at
0,4439,1515915625626736623,1515915625626736623-4439-6283415ac07ea,open,email,2022-05-19,2022-05-19 00:14:20
1,4439,1515915625490086521,1515915625490086521-4439-62834150016dd,open,email,2022-05-19,2022-05-19 00:39:34
2,4439,1515915625553578558,1515915625553578558-4439-6283415b36b4f,open,email,2022-05-19,2022-05-19 00:51:49
3,4439,1515915625553578558,1515915625553578558-4439-6283415b36b4f,click,email,2022-05-19,2022-05-19 00:52:20
4,4439,1515915625471518311,1515915625471518311-4439-628341570c133,open,email,2022-05-19,2022-05-19 00:56:52

(12739798, 7)
------------------------------

             client_id  target
0  1515915625468060902       0
1  1515915625468061003       1
2  1515915625468061099       0
3  1515915625468061100       0
4  1515915625468061170       0

(49849, 2)